FROM spark:3.5.8-java17-python3

USER root
COPY spark-conf.conf /opt/spark/conf/spark-defaults.conf

RUN curl -L -o /opt/spark/jars/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar

RUN curl -L -o /opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

RUN curl -L -o /opt/spark/jars/spark-snowflake_2.12-3.2.2.jar \
    https://repo1.maven.org/maven2/net/snowflake/spark-snowflake_2.12/3.2.2/spark-snowflake_2.12-3.2.2.jar

RUN curl -L -o /opt/spark/jars/snowflake-jdbc-4.0.2.jar \
    https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/4.0.2/snowflake-jdbc-4.0.2.jar

USER spark